import { Tool } from './types';

export const TOOLS: Tool[] = [
  {
    id: 'transcriber',
    name: 'AI Transcriber',
    description: 'Convert audio/video to text with timestamps.',
    icon: 'Mic',
    category: 'media',
    color: 'bg-blue-500',
  },
  {
    id: 'image-to-text',
    name: 'Image to Text',
    description: 'Extract text from images with layout preservation.',
    icon: 'Image',
    category: 'document',
    color: 'bg-orange-600',
  },
  {
    id: 'pdf-copilot',
    name: 'PDF Copilot',
    description: 'Chat with your PDFs and extract insights.',
    icon: 'FileText',
    category: 'document',
    color: 'bg-indigo-500',
  },
  {
    id: 'pdf-editor',
    name: 'AI PDF Editor',
    description: 'Edit PDF content using natural language.',
    icon: 'Edit3',
    category: 'document',
    color: 'bg-purple-500',
  },
  {
    id: 'whiteboard',
    name: 'AI Whiteboard',
    description: 'Refine sketches and diagrams with AI.',
    icon: 'Layout',
    category: 'media',
    color: 'bg-pink-500',
  },
  {
    id: 'organizer',
    name: 'Pure Organizer',
    description: 'Categorize and tag raw data automatically.',
    icon: 'Layers',
    category: 'data',
    color: 'bg-orange-500',
  },
  {
    id: 'planner',
    name: 'Strategic Planner',
    description: 'Generate executive reports and SWOT analysis.',
    icon: 'Target',
    category: 'planning',
    color: 'bg-emerald-500',
  },
  {
    id: 'translator',
    name: 'AI Translator',
    description: 'Context-aware translation in 100+ languages.',
    icon: 'Languages',
    category: 'writing',
    color: 'bg-cyan-500',
  },
  {
    id: 'grammar',
    name: 'Grammar Corrector',
    description: 'Fix grammar and adjust writing style.',
    icon: 'CheckCircle',
    category: 'writing',
    color: 'bg-green-500',
  },
  {
    id: 'pdf-manager',
    name: 'PDF Manager',
    description: 'Merge, split, and rotate PDF pages.',
    icon: 'Files',
    category: 'document',
    color: 'bg-rose-500',
  },
  {
    id: 'pdf-converter',
    name: 'PDF Converter',
    description: 'Convert between PDF and Images.',
    icon: 'Image',
    category: 'document',
    color: 'bg-amber-500',
  },
  {
    id: 'export-sheets',
    name: 'Export to Sheets',
    description: 'Extract tables to Excel or CSV.',
    icon: 'Table',
    category: 'data',
    color: 'bg-teal-500',
  },
  {
    id: 'video-audio',
    name: 'Video to Audio',
    description: 'Extract high-quality audio from video.',
    icon: 'Video',
    category: 'media',
    color: 'bg-red-500',
  },
  {
    id: 'tts',
    name: 'Text to Speech',
    description: 'Convert text to natural-sounding voices.',
    icon: 'Volume2',
    category: 'media',
    color: 'bg-violet-500',
  },
  {
    id: 'summarizer',
    name: 'Smart Summarizer',
    description: 'Concise summaries of long documents.',
    icon: 'Zap',
    category: 'writing',
    color: 'bg-yellow-500',
  },
];
